[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "SSGAC_ENV"
version = "0.0.0"
authors = [{ name = "Mahdi Mir", email = "imahdimir@gmail.com" }]
description = "SSGAC Environment VARs"
readme = "README.md"
dependencies = [
    "dotsi",
]
